---
apiVersion: v1
kind: Service
metadata:
  name: google-api
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: google-api